---
title: "STAT331 Final Project Proposal"
author: "Giovani Thai, William Gladden, Soren Paetau"
format: 
  html:
    self-contained: true
    code-tools: true
    code-fold: true
    toc: true
    number-sections: true
    smooth-scroll: true
editor: source
execute: 
  error: true
  echo: true
  message: false
  warning: false
---

```{r}
library(tidyverse)
```

## Project Proposal

```{r}
#importing data
sanitation.data <- read.csv("at_least_basic_sanitation_overall_access_percent.csv", check.names = F)
income.data <- read.csv("income_per_person_gdppercapita_ppp_inflation_adjusted.csv", check.names = F)
```

## Data Description

## Hypothesized Relationship

## Data Cleaning Process
replace na values with either median or mean (tbd)
```{r}
#data cleaning + joining
income.clean <- income.data |>
  pivot_longer(cols = `1799`:`2049`,
               names_to = "year",
               values_to = "income")
sanitation.clean <- snaitation.data |>
  picot_longer(cols = `1999`:`2019`,
               names_to = "year",
               values_to = "sanitation")

```

